extensions = ['recommonmark']

[tool.isort]
profile = "black"
src_paths = ["enet_plus"]
import_heading_thirdparty = "Third Party"
import_heading_firstparty = "ENetPlus"
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
float_to_top = true
sections= ["FUTURE", "STDLIB", "THIRDPARTY", "FIRSTPARTY", "LOCALFOLDER"]
